name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3	
    - name: Install modules
      run: pip install psutil
      shell: bash
    - name: Stress test
      run: python3 stress_test.py 60 180 5500
      shell: bash
