name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3	
    - name: Install modules
      run: pip install psutil
      shell: bash
    - name: Stress test
      run: python3 stress_test.py 60
      shell: bash
