name: Test hitting azure IMDS endpoint

on: workflow_dispatch

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest]
    continue-on-error: true 
    runs-on: ${{ matrix.os }}
    steps:
    - name: wget internal endpoint
      run: wget http://169.254.169.254/latest/metadata
      shell: bash
