name: Test hitting azure IMDS endpoint

on: workflow_dispatch

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest]
    continue-on-error: true 
    runs-on: ${{ matrix.os }}
    steps:
    - name: wget internal endpoint
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2017-08-01&format=text"
      shell: bash
